### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by KatieFl** [TonyFlury/SuffolkCycleDjango#17]
On the 'Sponsor Us' page, there is a paragraph starting with 'The Great Suffolk Cycle Ride'.  It is written in a white bold font and is therefore, very difficult to read. Please reconsider.

**Comment by TonyFlury** [comment]
Will review - the intention is that the name of the event always - but readability is important too.

**Comment by TonyFlury** [comment]
Removed special font in this case. Change merged into Master Branch

**Comment by TonyFlury** [comment]
Assigned to Katie for User Testing

**Comment by KatieFl** [comment]
Test is now legible
