### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by KatieFl** [TonyFlury/SuffolkCycleDjango#18]
I requested a password reset.  After entering my e-mail address, I was given a confirmation that a email would be sent to my account.  No e-mail was received.

**Comment by TonyFlury** [comment]
SMTP password is wrong - needs to be retested when fixed.

**Comment by TonyFlury** [comment]
Same root cause as #20.

**Comment by TonyFlury** [comment]
Should work - please retest
