### ISSUE TITLE
Newsletter Confirmation Page

### ISSUE THREAD

**Issue by KatieFl** [TonyFlury/SuffolkCycleDjango#19]
The thing wot happened when I hovered over 'READ MORE' causes the entire second line to move (probably because the 'read more' gets bigger.  This really isn't necessary, as the link is already written with a bold font and stands out and because the cursor turns into a hand when in the correct place.

**Comment by TonyFlury** [comment]
Will review the effect.

**Comment by TonyFlury** [comment]
Might remove Newsletter functionality completely.

**Comment by TonyFlury** [comment]
Have removed Newsletter Functionality - Should not be able to see any ability to sign up to Newsletter - /newsletter url should result in a 404

**Comment by KatieFl** [comment]
lookin' good buttercup
