### ISSUE TITLE
Sponsor us

### ISSUE THREAD

**Issue by KatieFl** [TonyFlury/SuffolkCycleDjango#21]
On sponsor ship form.  When you leave out your name, enter in other data and click save, you get the error message of 'This is a required field'  Please consider changing this to 'Name is a required field' so what you are talking about is obvious.

**Comment by TonyFlury** [comment]
Definitely a bug - even without analysis of the cause. Name has to be mandatory.

**Comment by TonyFlury** [comment]
Believed fixed in 0.1.0rc1 - needs to be re-tested
