### ISSUE TITLE
Registering - dashboard main page.

### ISSUE THREAD

**Issue by KatieFl** [TonyFlury/SuffolkCycleDjango#28]
After registering, there are 5 steps to complete.  These are bullet pointed on the web page.  I suggest numbering them, instead of bullet points to make it more clear that these are the steps to do.

**Comment by TonyFlury** [comment]
Will considering numbering - or making it clearer that these are the 5 steps. 
They weren't originally numbered as I didn't want to imply an ordering.

**Comment by TonyFlury** [comment]
Closed in Error

**Comment by TonyFlury** [comment]
Decided to number the items - and added clarification that they can be completed in any order

**Comment by TonyFlury** [comment]
Assigned to KatieFl - Please retest

**Comment by KatieFl** [comment]
Re-tested.  It is much easier to understand.  I have successfully pledged an amount and added a target and personal statement. I am unable to upload a pic or highlight a cycle route due to dominating facebook and twitter logos.

**Comment by KatieFl** [comment]
Giant FB and Twitter buttons are gone. I can successfully reach each page to add the required information.
