### ISSUE TITLE
Our Sponsors

### ISSUE THREAD

**Issue by KatieFl** [TonyFlury/SuffolkCycleDjango#29]
The 'our sponsors' button, under the sponsorship tab is inactive.

**Comment by TonyFlury** [comment]
Need a new page - will develop.

**Comment by TonyFlury** [comment]
New Page Developed - included in 0.1.0rc3

**Comment by TonyFlury** [comment]
Assigned to KatieFl for User Testing.

**Comment by KatieFl** [comment]
You need to add CabSmart as a sponsor, but the button now works

**Comment by KatieFl** [comment]
Yay
