### ISSUE TITLE
Fundme share to Facebook

### ISSUE THREAD

**Issue by TonyFlury** [TonyFlury/SuffolkCycleDjango#32]
Need to ensure that FundMe page can be correctly share to facebook.

Need a proper Facebook Icon on the Mockup page - share from Mockup Only.

**Comment by TonyFlury** [comment]
Facebook and twitter share buttons on Fundme Mockup page.
Assigned to KatieFl for User Testing

**Comment by KatieFl** [comment]
This does share to facebook.  However, when  using the links directly, after clicking share, it takes me to a blank page (similar to using the share fb button).

**Comment by TonyFlury** [comment]
Please retest and close as appropriate.

**Comment by TonyFlury** [comment]
Agreed closed
