### ISSUE TITLE
Facebook share without Javascript

### ISSUE THREAD

**Issue by TonyFlury** [TonyFlury/SuffolkCycleDjango#33]
Implement Facebook Share button - without the complex button and JS library... uggh

**Comment by TonyFlury** [comment]
This enhancement has been completed - need to test that the Facebook and Twitter icons on the home page (and all other pages) shares the Homepage to the relevant Social Media - with a correct generic message.

The only exception is the FundMe page (specifically the Fundme Mockup page from the Dashboard) where the FB and twitter message should be specific to the user - and link to the FundMe page.
Also the Fundme Facebook button should ideally share both the Default Icon AND the users photo as image icons.

**Comment by KatieFl** [comment]
I attempted to share and I was taken to the following URL:
https://www.facebook.com/dialog/return/close?#_=_

It was a blank, white page.

**Comment by KatieFl** [comment]
please note: it did share to my timeline, when I went to facebook manually.

**Comment by TonyFlury** [comment]
Please retest - issues should be resolved from both the normal pages and the FundMe mockup.

**Comment by KatieFl** [comment]
When I used the facebook share button I was taken to a facebook error page. Sorry

**Comment by TonyFlury** [comment]
Finally working - yay !
