### ISSUE TITLE
Facebook Sharing and Fund-me

### ISSUE THREAD

**Issue by KatieFl** [TonyFlury/SuffolkCycleDjango#41]
I attempted to share and I was taken to the following URL:
https://www.facebook.com/dialog/return/close?#_=_

It was a blank, white page. It does share to facebook, though. Same with the 'Fundme Share'

**Comment by TonyFlury** [comment]
Now corrected - please retest

**Comment by KatieFl** [comment]
FB button takes me to a a fb error page.  In the case of FundMe Share, I was taken to a fb error page saying, 'Error

Warning
App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.'

**Comment by KatieFl** [comment]
it works
