### ISSUE TITLE
User confirmation email missing fill in data

### ISSUE THREAD

**Issue by TonyFlury** [TonyFlury/SuffolkCycleDjango#9]
User confirmation email on registration has no filled in data (username etc).

**Comment by KatieFl** [comment]
Could not test on 16/2/16 as I was already a registered user.

**Comment by KatieFl** [comment]
I registered as Katie Clark, no e-mail confirmation was received.

**Comment by TonyFlury** [comment]
Please confirm that the email you received at the last registration contained all the correct details.

**Comment by KatieFl** [comment]
Correct
